apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-simple-kubectl-task
spec:
  inputs:
    resources:
    - name: git-source
      type: git
    - name: image-out
      type: image
    params:
    - name: event-type
    - name: branch
  steps:
  - name: check-event-type
    image: ubuntu
    command: ['/bin/bash']
    args: ['if [ $(EVENT_TYPE) == "pull" ] && [ $(BRANCH) != "master" ];then exit 0;fi']
    env:
    - name: EVENT_TYPE
      value: $(inputs.params.event-type)
    - name: BRANCH
      value: $(inputs.params.branch)
  - name: modify-yaml
    image: ubuntu
    command: ['/bin/bash']
    args: ['-c', 'find ./git-source/config -type f -exec sed -i -e s!"image: PIPELINE_REPLACE:latest"!"image: $(IMG)"!g {} \;']
    env:
    - name: IMG
      value: $(inputs.resources.image-out.url)
  - name: install-new
    image: lachlanevenson/k8s-kubectl
    command: ['kubectl']
    args:
    - 'apply'
    - '-f'
    - './git-source/config'
